function [E1,R1] = GSSOR2M(E0,RHS,R,Z,NIT,ome)
dr = R(2,1) - R(1,1);dr2 = dr*dr;NR = length(R(:,1));NZ = length(Z(1,:));
dz = Z(1,2) - Z(1,1);dz2 = dz*dz;
Psi_S0 = E0;Psis_tmp = E0;
iter=1;

while( iter <= NIT )
    % - 三点中心差分
    %     for j = 2:NZ-1
    %         for  i= 2:NR-1
    %             Psis_tmp(i,j)=((Psi_S0(i+1,j)+Psi_S0(i-1,j))/dr2+(Psi_S0(i,j+1)+...
    %                 Psi_S0(i,j-1))/dz2-0.5*(Psi_S0(i+1,j)-Psi_S0(i-1,j))/...
    %                 (R(i,j)*dr)-RHS(i,j))/(2/dr2+2/dz2);
    %         end
    %     end
    % - 三点中心差分 Z方向向量
    %     for i = 2:NR-1
    %         Psis_tmp(i,2:NZ-1) = ((1 - 0.5*dr./R(i,2:NZ-1)).*Psi_S0(i+1,2:NZ-1) +...
    %                               (1 + 0.5*dr./R(i,2:NZ-1)).*Psi_S0(i-1,2:NZ-1) +...
    %                    dr2/dz2.*( Psi_S0(i,3:NZ) + Psi_S0(i,1:NZ-2) ) - dr2*RHS(i,2:NZ-1))/...
    %                            (2*(1 + dr2/dz2));
    %     end
    % - 三点差分 奇数迭代左上->右下;偶数次右下->左上
    indr = 2:NR-1;indz = 2:NZ-1;indrr = flip(indr);indrz = flip(indz);
    if ( mod(NIT,2) == 1 )%奇数迭代
        for i = indr
            for j = indz
                Psis_tmp(i,j) = ((1 - 0.5*dr./R(i,1)).*Psi_S0(i+1,j) +...
                    (1 + 0.5*dr./R(i,1)).*Psi_S0(i-1,j) +...
                    dr2/dz2.*( Psi_S0(i,j+1) + Psi_S0(i,j-1) ) - dr2*RHS(i,j))/...
                    (2*(1 + dr2/dz2));
            end
        end
    elseif ( mod(NIT,2) == 0 )%偶数迭代
        for i = indrr
            for j = indrz
                Psis_tmp(i,j) = ((1 - 0.5*dr./R(i,1)).*Psi_S0(i+1,j) +...
                    (1 + 0.5*dr./R(i,1)).*Psi_S0(i-1,j) +...
                    dr2/dz2.*( Psi_S0(i,j+1) + Psi_S0(i,j-1) ) - dr2*RHS(i,j))/...
                    (2*(1 + dr2/dz2));
            end
        end
    end
    
    
    % - 五点中心差分
    % - 3：end-2 内部点
%     for i = 3:NR-2
%         Psis_tmp(i,3:NZ-2) =( ( (1 + dr./R(i,3:NZ-2)).*Psi_S0(i-2,3:NZ-2) -...
%                               8*(2 + dr./R(i,3:NZ-2)).*Psi_S0(i-1,3:NZ-2) -...
%                               8*(2 - dr./R(i,3:NZ-2)).*Psi_S0(i+1,3:NZ-2) +...
%                                 (1 - dr./R(i,3:NZ-2)).*Psi_S0(i+2,3:NZ-2)) +...
%                        dr2/dz2*( Psi_S0(i,1:NZ-4) - 16*Psi_S0(i,2:NZ-3) -...
%                                  16*Psi_S0(i,4:NZ-1) + Psi_S0(i,5:NZ) ) +...
%                               12*dr2*RHS(i,3:NZ-2) )/(-30*(1+dr2/dz2));
%     end
%     % - indr = 2:end-1 indz = 2 or end - 1
%     for i = 2:NR-1
%         Psis_tmp(i,2)    = ((1 - 0.5*dr./R(i,2)).*Psi_S0(i+1,2) +...
%                             (1 + 0.5*dr./R(i,2)).*Psi_S0(i-1,2) +...
%                    dr2/dz2.*( Psi_S0(i,3) + Psi_S0(i,1) ) - dr2*RHS(i,2))/...
%                            (2*(1 + dr2/dz2));
% 
%         Psis_tmp(i,NZ-1) = ((1 - 0.5*dr./R(i,NZ-1)).*Psi_S0(i+1,NZ-1) +...
%                             (1 + 0.5*dr./R(i,NZ-1)).*Psi_S0(i-1,NZ-1) +...
%                    dr2/dz2.*( Psi_S0(i,NZ) + Psi_S0(i,NZ-2) ) - dr2*RHS(i,NZ-1))/...
%                            (2*(1 + dr2/dz2));
%     end
%     % - indr = 2 or end - 1 indz = 3:end - 2
%     Psis_tmp(2,3:NZ-2)    = ( (1 - 0.5*dr./R(2,3:NZ-2)).*Psi_S0(3,3:NZ-2) +...
%                               (1 + 0.5*dr./R(2,3:NZ-2)).*Psi_S0(1,3:NZ-2) +...
%                      dr2/dz2.*( Psi_S0(2,4:NZ-1) + Psi_S0(2,2:NZ-3) ) -...
%                              dr2*RHS(2,3:NZ-2) )/(2*(1+dr2/dz2));
%     
%     
%     Psis_tmp(NR-1,3:NZ-2) = ( (1 - 0.5*dr./R(NR-1,3:NZ-2)).*Psi_S0(NR,3:NZ-2) +...
%                               (1 + 0.5*dr./R(NR-1,3:NZ-2)).*Psi_S0(NR-2,3:NZ-2) +...
%                      dr2/dz2.*( Psi_S0(NR-1,4:NZ-1) + Psi_S0(NR-1,2:NZ-3) ) -...
%                              dr2*RHS(NR-1,3:NZ-2) )/(2*(1+dr2/dz2));

    Psi_S0 = ome*Psis_tmp + (1 - ome)*Psi_S0;%改变边界
    iter = iter + 1;
end
% --------- 直接返回残差 ---------- %
E1  = Psi_S0;
RES = zeros(size(R));R1 = RES;

RES(2:end-1,2:end-1) = ( E1(3:end,2:end-1) - 2*E1(2:end-1,2:end-1) + E1(1:end-2,2:end-1) )/dr2 - ...
    0.5*( E1(3:end,2:end-1) - E1(1:end-2,2:end-1) )./(R(2:end-1,2:end-1)*dr) + ...
    ( E1(2:end-1,3:end) - 2*E1(2:end-1,2:end-1) + E1(2:end-1,1:end-2) )/dz2;

R1(2:end-1,2:end-1) = RHS(2:end-1,2:end-1) - RES(2:end-1,2:end-1);